import Image from "next/image";
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="bg-[#191919] text-gray-300">
      <div className="mx-auto max-w-7xl px-6 py-16 text-center">

        {/* Medallion Logo */}
        <div className="mb-8 flex justify-center">
          <Image
            src="/medallion2.png" // replace with your image
            alt="MLS Medallion Club Member"
            width={180}
            height={180}
          />
        </div>

        {/* Footer Navigation */}
        

        {/* Disclaimer */}
        <p className="mx-auto mb-10 max-w-5xl text-xs leading-relaxed text-white">
          Copyright © 2026 All rights reserved. Disclaimer: This representation
          is based in whole or in part on data generated by the Chilliwack &
          District Real Estate Board, Fraser Valley Real Estate Board or Real
          Estate Board of Greater Vancouver which assumes no responsibility for
          its accuracy. Listing information last updated on 1/21/2026 at 3:44am
          MDT. The trademarks REALTOR®, REALTORS® and the REALTOR® logo are
          controlled by The Canadian Real Estate Association (CREA) and identify
          real estate professionals who are members of CREA. The trademarks MLS®,
          Multiple Listing Service® and the associated logos are owned by The
          Canadian Real Estate Association (CREA) and identify the quality of
          services provided by real estate professionals who are members of CREA.
          Used under license.
        </p>

        {/* Agent Info */}
        <div className="mb-6 text-xs text-white">
          <p>
             Sales Representative | TRG The Residential Group
            Realty  property management Independently Owned & Operated | 604-629-6100 | #101 – 1965
            West 4th Avenue Vancouver, British Columbia V6J 1M8
          </p>
          <p className="mt-2 text-md ">
            <Link href="/terms" className="hover:text-white">Terms of Use</Link>
            {" | "}
            <Link href="/privacy" className="hover:text-white">Privacy Policy</Link>
            {" | "}
            <Link href="/account" className="hover:text-white">My Account</Link>
            {" | "}
            <Link href="/logout" className="hover:text-white">Logout</Link>
          </p>
        </div>

      

      </div>
    </footer>
  );
}
